"""skill.json matches the script, the data file is the one recorded, and bad input stops with exit 3."""

import gzip
import hashlib
import json
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import personal_report  # noqa: E402
import skillkit  # noqa: E402
from genotype_file import GenotypeFileError, read_genotype_file  # noqa: E402

MANIFEST = json.loads((ROOT / "skill.json").read_text(encoding="utf-8"))
SCRIPT = (ROOT / "scripts" / "personal_report.py").read_text(encoding="utf-8")

HEADER_23ANDME = (
    "# This data file generated by 23andMe at: Thu Jan 01 00:00:00 2026\n"
    "# We are using reference human assembly build 37 (also known as Annotation Release 104).\n"
    "# rsid\tchromosome\tposition\tgenotype\n"
)


def _file(tmp_path, text, name="genome.txt"):
    path = tmp_path / name
    path.write_text(text, encoding="utf-8")
    return path


def test_every_declared_flag_is_parsed_by_the_script():
    for spec in MANIFEST["inputs"]:
        assert f'"{spec["flag"]}"' in SCRIPT, spec["key"]
    assert '"--medications"' in SCRIPT and MANIFEST["entry"]["medications_flag"] == "--medications"
    assert '"--out"' in SCRIPT


def test_declared_outputs_are_written(tmp_path):
    path = _file(tmp_path, HEADER_23ANDME + "rs4244285\t10\t96541616\tAG\n")
    personal_report.write_report(tmp_path / "out", path)
    result = json.loads((tmp_path / "out" / "result.json").read_text(encoding="utf-8"))
    assert set(result["outputs"]) == {item["key"] for item in MANIFEST["outputs"]}
    assert result["outputs"]["cyp2c19_phenotype"]["value"] == "Intermediate Metabolizer"


def test_data_file_hash_matches_manifest():
    for item in MANIFEST["data_files"]:
        digest = hashlib.sha256((ROOT / item["path"]).read_bytes()).hexdigest()
        assert digest == item["sha256"], item["path"]
    assert (ROOT / "data" / "LICENSE-CPIC.md").exists()


def test_paper_card_cites_caudle_2017(tmp_path):
    path = _file(tmp_path, HEADER_23ANDME + "rs4244285\t10\t96541616\tGG\n")
    text = personal_report.write_report(tmp_path / "out", path).read_text(encoding="utf-8")
    card = text.split("## 基因结果", 1)[0]
    assert "10.1038/gim.2016.87" in card and "Caudle" in card
    assert "10.1002/cpt.2526" in card  # clopidogrel guideline in the card notes


def _exit(argv):
    return personal_report.main(argv)


def test_no_input_exits_3(tmp_path):
    assert _exit(["--out", str(tmp_path / "out")]) == skillkit.EXIT_INPUT_PROBLEM
    problems = json.loads((tmp_path / "out" / "problems.json").read_text(encoding="utf-8"))
    assert problems["problems"][0]["key"] == "genotype"


def test_not_a_genotype_file_exits_3(tmp_path):
    path = _file(tmp_path, "项目,结果,单位\n白蛋白,45,g/L\n", "labs.csv")
    assert _exit(["--genotype", str(path), "--out", str(tmp_path / "out")]) == skillkit.EXIT_INPUT_PROBLEM
    assert "没有找到基因型行" in (tmp_path / "out" / "report.md").read_text(encoding="utf-8")


def test_file_without_any_drug_gene_site_exits_3(tmp_path):
    path = _file(tmp_path, HEADER_23ANDME + "rs4477212\t1\t82154\tAA\nrs3094315\t1\t752566\tAG\n")
    assert _exit(["--genotype", str(path), "--out", str(tmp_path / "out")]) == skillkit.EXIT_INPUT_PROBLEM
    assert "一个也没有" in (tmp_path / "out" / "report.md").read_text(encoding="utf-8")


def test_bad_clinical_line_exits_3(tmp_path):
    path = _file(tmp_path, "CYP2C19 慢代谢\n", "dip.txt")
    assert _exit(["--diplotypes", str(path), "--out", str(tmp_path / "out")]) == skillkit.EXIT_INPUT_PROBLEM


def test_missing_file_exits_3(tmp_path):
    assert _exit(["--genotype", str(tmp_path / "nope.txt"), "--out", str(tmp_path / "out")]) == skillkit.EXIT_INPUT_PROBLEM


def test_good_file_exits_0(tmp_path):
    path = _file(tmp_path, HEADER_23ANDME + "rs4244285\t10\t96541616\tAG\n")
    assert _exit(["--genotype", str(path), "--out", str(tmp_path / "out")]) == 0
    assert not (tmp_path / "out" / "problems.json").exists()


# --- file formats -------------------------------------------------------------


def test_23andme_rows_and_no_calls(tmp_path):
    path = _file(tmp_path, HEADER_23ANDME + "rs4244285\t10\t96541616\tAG\nrs4986893\t10\t96540410\t--\nrs41303343\t7\t99250393\tDI\n")
    parsed = read_genotype_file(path)
    assert parsed.format == "23andme" and parsed.build_note == "GRCh37"
    assert parsed.genotype("rs4244285") == "AG"
    assert "rs4986893" in parsed.no_calls
    assert parsed.genotype("rs41303343") == "DI"


def test_wegene_header_and_two_letter_calls(tmp_path):
    text = "# WeGene raw data\n# rsid\tchromosome\tposition\tgenotype\nrs4244285\t10\t96541616\tAA\nrs2032598\tY\t2821400\tTT\n"
    parsed = read_genotype_file(_file(tmp_path, text))
    assert parsed.format == "wegene"
    assert parsed.genotype("rs4244285") == "AA"


def test_ancestrydna_five_columns(tmp_path):
    text = "#AncestryDNA raw data download\nrsid\tchromosome\tposition\tallele1\tallele2\nrs4244285\t10\t96541616\tG\tA\n"
    parsed = read_genotype_file(_file(tmp_path, text))
    assert parsed.format == "ancestrydna" and parsed.genotype("rs4244285") == "GA"


def test_comma_gz_and_zip(tmp_path):
    csv_text = "rsid,chromosome,position,genotype\nrs4244285,10,96541616,AG\n"
    assert read_genotype_file(_file(tmp_path, csv_text, "a.csv")).genotype("rs4244285") == "AG"
    gz = tmp_path / "a.txt.gz"
    gz.write_bytes(gzip.compress((HEADER_23ANDME + "rs4244285\t10\t96541616\tAG\n").encode()))
    assert read_genotype_file(gz).genotype("rs4244285") == "AG"
    zipped = tmp_path / "a.zip"
    with zipfile.ZipFile(zipped, "w") as archive:
        archive.writestr("genome.txt", HEADER_23ANDME + "rs4244285\t10\t96541616\tAG\n")
    assert read_genotype_file(zipped).genotype("rs4244285") == "AG"


def test_empty_file_is_an_error(tmp_path):
    try:
        read_genotype_file(_file(tmp_path, "# only comments\n"))
    except GenotypeFileError as error:
        assert "没有找到基因型行" in error.message_zh
    else:
        raise AssertionError("expected GenotypeFileError")


def test_shared_parser_copies_are_identical():
    other = ROOT.parent / "nutrigenetic-variant-panel" / "scripts" / "genotype_file.py"
    if other.exists():
        assert other.read_bytes() == (ROOT / "scripts" / "genotype_file.py").read_bytes()

