"""The whole report on a synthetic genotype file: wording, no doses, medicines."""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import personal_report  # noqa: E402
from cpic_calls import load_tables  # noqa: E402
from presets import DOCTOR_LINE, DRUGS  # noqa: E402

SYNTHETIC = """# This data file generated by 23andMe at: Thu Jan 01 00:00:00 2026
# We are using reference human assembly build 37 (also known as Annotation Release 104).
# rsid	chromosome	position	genotype
rs4477212	1	82154	AA
rs4244285	10	96541616	AA
rs4986893	10	96540410	GG
rs28399504	10	96522463	AA
rs12248560	10	96521657	CC
rs1799853	10	96702047	CC
rs1057910	10	96741053	AA
rs9923231	16	31107689	TT
rs4149056	12	21331549	TT
rs2231142	4	89052323	GT
rs1800462	6	18143955	CC
rs1800460	6	18139228	CC
rs1142345	6	18130918	TT
rs116855232	13	48619855	CC
rs3918290	1	97915614	CC
rs55886062	1	98039419	AA
rs67376798	1	97547947	TT
rs75017182	1	98045449	GG
rs776746	7	99270539	CC
rs10264272	7	99262835	CC
"""


def run(tmp_path, meds=None, drugs=None, diplotypes=None):
    genotype = tmp_path / "genome.txt"
    genotype.write_text(SYNTHETIC, encoding="utf-8")
    medications = None
    if meds:
        medications = tmp_path / "meds.txt"
        medications.write_text("\n".join(meds) + "\n", encoding="utf-8")
    clinical = None
    if diplotypes:
        clinical = tmp_path / "dip.txt"
        clinical.write_text("\n".join(diplotypes) + "\n", encoding="utf-8")
    path = personal_report.write_report(tmp_path / "out", genotype, clinical, medications, drugs or [])
    return path.read_text(encoding="utf-8"), json.loads((tmp_path / "out" / "result.json").read_text(encoding="utf-8"))


def test_poor_metabolizer_on_clopidogrel_is_sent_to_the_prescriber(tmp_path):
    text, result = run(tmp_path, meds=["波立维 75mg", "二甲双胍"])
    assert result["outputs"]["cyp2c19_phenotype"]["value"] == "Poor Metabolizer"
    section = text.split("## 你正在用的药", 1)[1].split("## 基因结果", 1)[0]
    assert "**氯吡格雷**" in section and "CPIC 建议考虑换药或避免使用" in section
    assert DOCTOR_LINE in section
    assert "二甲双胍：CPIC 这几份指南里没有这个名字。不能据此停" in section
    assert "clopidogrel" in result["outputs"]["drugs_to_discuss"]["value"]


def test_report_never_prints_a_dose_or_cpic_dosing_text(tmp_path):
    text, _ = run(tmp_path, meds=["阿托伐他汀钙片 20mg"], diplotypes=["CYP2D6 *1/*10", "HLA-B*58:01 阳性"])
    body = text.split("## 你正在用的药", 1)[1]
    assert not re.search(r"\d+(\.\d+)?\s*(mg|毫克|mg/day|mg/kg)", body, re.IGNORECASE)
    tables = load_tables()
    for entry in tables["drugs"].values():
        for row in entry["rows"]:
            if len(row["recommendation"]) > 30:
                assert row["recommendation"][:30] not in text


def test_every_avoid_or_caution_block_has_the_doctor_line(tmp_path):
    text, _ = run(tmp_path)
    section = text.split("## 需要先和医生或药师核对的药", 1)[1].split("## CPIC 认为可以按常规用法的药", 1)[0]
    blocks = [block for block in section.split("\n- **")[1:]]
    assert blocks
    for block in blocks:
        assert DOCTOR_LINE in block, block[:60]


def test_cyp2d6_and_hla_limits_are_stated(tmp_path):
    text, result = run(tmp_path)
    assert "## 芯片数据判断不了的" in text
    assert "*36+*10" in text and "拷贝" in text
    assert "需要 CYP2D6：" in text
    assert result["outputs"]["cyp2d6_phenotype"]["value"] is None


def test_clinical_cyp2d6_result_is_used(tmp_path):
    text, result = run(tmp_path, diplotypes=["CYP2D6 *10/*10"])
    assert result["outputs"]["cyp2d6_phenotype"]["value"] == "Intermediate Metabolizer (activity score 0.5)"
    assert "CYP2D6 中间代谢型（活性分 0.5）" in text


def test_single_drug_question(tmp_path):
    text, _ = run(tmp_path, drugs=["可定", "某某胶囊"])
    asked = text.split("## 你问的药", 1)[1].split("## 你正在用的药", 1)[0]
    assert "**瑞舒伐他汀**" in asked
    assert "某某胶囊：CPIC 这几份指南里没有这个名字" in asked


def test_medicine_names_match_the_right_drug():
    assert personal_report.match_drug("右兰索拉唑肠溶胶囊") == "dexlansoprazole"
    assert personal_report.match_drug("兰索拉唑") == "lansoprazole"
    assert personal_report.match_drug("硫酸氢氯吡格雷片 75mg") == "clopidogrel"
    assert personal_report.match_drug("Crestor") == "rosuvastatin"
    assert personal_report.match_drug("艾司奥美拉唑") is None or personal_report.match_drug("艾司奥美拉唑") == "omeprazole"
    assert personal_report.match_drug("二甲双胍") is None


def test_every_covered_drug_has_a_chinese_name():
    tables = load_tables()
    assert set(tables["drugs"]) <= set(DRUGS)
